import { Inter } from 'next/font/google'
import './globals.css'
import { SnackbarProvider } from '@/app/components/layouts/SnackbarProvider/SnackbarProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <SnackbarProvider>
        <body className={inter.className}>{children}</body>
      </SnackbarProvider>
    </html>
  )
}
