name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          cd Raika/backend
          gem install bundler
          bundle install

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          cd Raika/backend
          bundle exec rails test

      - name: Run Rubocop
        run: |
          cd Raika/backend
          bundle exec rubocop
